import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import puppeteer from "puppeteer";
import { marked } from "marked";

export async function GET(req: Request, { params }: { params: Promise<{ sessionId: string }> }) {
  try {
    const p = await params;
    const { sessionId } = p;

    // Fetch the target report and session data
    const session = await prisma.session.findUnique({
      where: { id: sessionId }
    });
    
    if (!session) {
      return new NextResponse("Session not found", { status: 404 });
    }

    const report = await prisma.report.findFirst({
      where: { sessionId },
      orderBy: { generatedAt: "desc" },
    });

    if (!report) {
      return new NextResponse("Report not found. Generate one first.", { status: 404 });
    }

    // Convert markdown into HTML securely and cleanly using marked
    const markdownHtml = await marked(report.content);

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>${session.name} - Instructor Report</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
              line-height: 1.6;
              color: #334155; // slate-700
              max-width: 800px;
              margin: 0 auto;
              padding: 40px;
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #e2e8f0; // slate-200
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              color: #0f172a; // slate-900
              margin: 0 0 10px 0;
            }
            .header p {
              color: #64748b; // slate-500
              margin: 0;
              font-size: 14px;
            }
            h2, h3, h4 {
              color: #0f172a;
              margin-top: 1.5em;
              margin-bottom: 0.5em;
            }
            h2 {
              border-bottom: 1px solid #e2e8f0;
              padding-bottom: 0.3em;
            }
            ul, ol {
              padding-left: 20px;
            }
            li {
              margin-bottom: 0.5em;
            }
            .footer {
              margin-top: 50px;
              text-align: center;
              color: #94a3b8; // slate-400
              font-size: 12px;
              border-top: 1px solid #e2e8f0;
              padding-top: 20px;
            }
            blockquote {
              border-left: 4px solid #cbd5e1; // slate-300
              padding-left: 15px;
              color: #475569; // slate-600
              font-style: italic;
              margin: 1.5em 0;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${session.name}</h1>
            <p>Session Report</p>
            <p>Generated: ${new Date(report.generatedAt).toLocaleString()}</p>
          </div>
          <div class="content">
            ${markdownHtml}
          </div>
          <div class="footer">
            Generated by Socratic Tutor
          </div>
        </body>
      </html>
    `;

    // Launch puppeteer to generate the PDF Buffer
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    const pdfBuffer = await page.pdf({
      format: 'A4',
      margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' },
      printBackground: true
    });
    await browser.close();

    // Prepare HTTP response headers for a PDF download
    const headers = new Headers();
    headers.set('Content-Type', 'application/pdf');
    headers.set(
      'Content-Disposition',
      `attachment; filename="Report-${session.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf"`
    );

    return new NextResponse(pdfBuffer, { status: 200, headers });
    
  } catch (error: any) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to export PDF", details: error.message },
      { status: 500 }
    );
  }
}
